export const AppActionTypes = {
  AUTHENTICATE_USER: 'AUTHENTICATE_USER',
  CREATE_NEWUSER: 'CREATE_NEWUSER',
  GET_PLAYLIST_ROUTINES: 'GET_PLAYLIST_ROUTINES',
  GET_ROUTINE_DETAILS: 'GET_ROUTINE_DETAILS',
};
