export const EVENTS = {
  USER_AUTHENTICATED: 'USER_AUTHENTICATED',
  USER_CREATED: 'USER_CREATED',
  PLAYLIST_ROUTINES_RECEIVED: 'PLAYLIST_ROUTINES_RECEIVED',
  ROUTINE_DETAILS_RECEIVED: 'ROUTINE_DETAILS_RECEIVED',
  TRAINER_DETAILS_RECEIVED: 'TRAINER_DETAILS_RECEIVED',
  ROUTINE_ADDED_TO_PLAYLIST: 'ROUTINE_ADDED_TO_PLAYLIST',
  TRAINER_FAVORITE_TOGGLED: 'TRAINER_FAVORITE_TOGGLED',
};
